version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    reanalysis_downscaler:
      image: jpxkqx/deep-oc-reanalysis_downscaler
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    reanalysis_downscaler-gpu:
      image: jpxkqx/deep-oc-reanalysis_downscaler:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    reanalysis_downscaler-rclone:
      extends:
        service: reanalysis_downscaler
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
